2025-09-27 18:35:50.571 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-09-27 22:34:09.722 ERROR (SyncWorker_2) [annotatedyaml.loader] while parsing a block mapping
  in "/config/sensors.yaml", line 1, column 3
expected <block end>, but found '<block mapping start>'
  in "/config/sensors.yaml", line 10, column 4
2025-09-27 22:45:12.422 ERROR (MainThread) [homeassistant.components.oralb] B4:35:22:CE:AB:BF: Failure while polling
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/active_update_processor.py", line 122, in _async_poll
    update = await self._async_poll_data(self._last_service_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/active_update_processor.py", line 115, in _async_poll_data
    return await self._poll_method(last_service_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/oralb/__init__.py", line 67, in _async_poll
    return await data.async_poll(connectable_device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/oralb_ble/parser.py", line 371, in async_poll
    await client.disconnect()
  File "/usr/local/lib/python3.13/site-packages/habluetooth/wrappers.py", line 510, in disconnect
    await self._backend.disconnect()
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/client.py", line 450, in disconnect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/dbus_fast/aio/message_bus.py", line 398, in call
    await future
  File "src/dbus_fast/aio/message_reader.py", line 23, in dbus_fast.aio.message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 868, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 732, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 453, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
  File "src/dbus_fast/_private/unmarshaller.py", line 393, in dbus_fast._private.unmarshaller.Unmarshaller._read_sock_with_fds
EOFError
2025-09-27 22:45:29.775 WARNING (MainThread) [homeassistant.components.media_player] Error retrieving proxied image from http://192.168.2.8:1400/getaa?u=x-rincon-mp3radio://stream-uk1.radioparadise.com/aac-320&v=17
2025-09-27 22:48:16.020 ERROR (SyncWorker_5) [annotatedyaml.loader] while parsing a block mapping
  in "/config/sensors.yaml", line 2, column 3
expected <block end>, but found '-'
  in "/config/sensors.yaml", line 3, column 3
2025-09-27 22:52:47.490 ERROR (MainThread) [frontend.js.modern.202509035] Uncaught error from Firefox 143.0 on Ubuntu
TypeError: can't access property "startFocus", this._getItemAtIndex(...).rippleHandlers is undefined
_setFocusFirstListItem (src/dialogs/quick-bar/ha-quick-bar.ts:541:9)
call (src/lit-html.ts:2109:28)
2025-09-27 22:56:10.787 WARNING (MainThread) [homeassistant.components.media_player] Error retrieving proxied image from http://192.168.2.8:1400/getaa?u=x-rincon-mp3radio://playerservices.streamtheworld.com/api/livestream-redirect/KINK.mp3&v=17
2025-09-27 22:59:08.600 ERROR (MainThread) [homeassistant.config] Invalid config for 'sensor' at sensors.yaml, line 1: required key 'platform' not provided, please check the docs at https://www.home-assistant.io/integrations/sensor
2025-09-27 22:59:08.601 ERROR (MainThread) [homeassistant.config] Invalid config for 'sensor' at sensors.yaml, line 3: required key 'platform' not provided, please check the docs at https://www.home-assistant.io/integrations/sensor
2025-09-27 22:59:08.601 ERROR (MainThread) [homeassistant.config] Invalid config for 'sensor' from integration 'template' at sensors.yaml, line 2: required key 'sensors' not provided, please check the docs at https://www.home-assistant.io/integrations/template
